language: C++
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y install autoconf2.13 build-essential ccache python-dev python-pip python-setuptools unzip uuid zip
script:
  make build
cache:
  directories:
   - build 
