language: C++
sudo: required
dist: trusty
before_install:
#  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update
  - sudo apt-get install python-pip python-dev
  - sudo pip install mercurial
#  - sudo apt-get install -y mercurial autoconf2.13 build-essential ccache python-dev python-pip python-setuptools unzip uuid zip libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdbus-glib-1-dev libgconf2-dev libgtk2.0-dev libgtk-3-dev libiw-dev libnotify-dev libpulse-dev libxt-dev mesa-common-dev python-dbus yasm xvfb
script:
  make build
cache:
  directories:
   - build
