language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
script:
  make build
cache:
  directories:
   - build 
notifications:
  irc:
    channels:
     - "irc.mozilla.org#ronin"
    use_notice: true

   email:
   - loic@cuguen.org
